language: java

jdk:
- oraclejdk8

env:
  global:
    - COVERALLS_REPO_TOKEN=apBClVR2Bxy20Z1tLFIzSKJuURh7sVCpM

before_install:
- sudo chmod +x ./gradlew ./gradlew.bat
- gradle wrapper

after_success:
- gradle cobertura coveralls