language: java

jdk:
- oraclejdk8

env:
  global:
    - CI_NAME=travis-ci
    - COVERALLS_REPO_TOKEN=J7CUVVb2o5hlnRFmC4g1wZpAklsXFjAIj

before_install:
- sudo chmod +x ./gradlew ./gradlew.bat
- gradle wrapper

after_success:
- gradle cobertura coveralls